# global parameters
project_name: 'dataset-knowledge_instensity-np128'
dataset_path: '/apdcephfs_cq8/share_2906397/users/wangkuang/pretrain_text_data/knowledge_intensive/baike_900w/processed_test_bench.jsonl'
ds_cache_dir: "./ds_cache_dir"
temp_dir: "./ds_temp_dir"
text_keys: 'raw_content'   
export_path: './outputs/test/zh/rule-np128/output.jsonl'

np: 176  # number of subprocess to process your dataset
open_tracer: true
# executor_type: 'ray'  # 将执行器类型设置为 "ray"
# ray_address: 'auto'  # 设置为自动 Ray 地址


# process schedule
# a list of several process operators with their arguments
process:
  - clean_email_mapper:                                     # remove emails from text.
  - clean_html_mapper:                                      # remove html formats form text.
  - clean_ip_mapper:                                        # remove ip addresses from text.
  - clean_links_mapper:                                     # remove web links from text.
  - clean_copyright_mapper:                                 # remove copyright comments.
  - fix_unicode_mapper:
  - punctuation_normalization_mapper:
  - whitespace_normalization_mapper:

  - alphanumeric_filter:
      tokenization: false
      min_ratio: 0.5 
      max_ratio: 0.9   # >3sigma (0.867)
  - average_line_length_filter:  # for code
      max_len: 3000  # >3sigma (1277)
  - maximum_line_length_filter:  # for code
      max_len: 4000  # >3sigma (2017)
  - character_repetition_filter:
      rep_len: 10
      max_ratio: 0.6  # >3sigma (0.168)
  - flagged_words_filter: # 104576967
      lang: en
      tokenization: true
      use_words_aug: true
      max_ratio: 0.02
  - text_length_filter: # 104573711
       min_len: 30
       max_len: 18221 # 3sigma
  - special_characters_filter:
      max_ratio: 0.5  # > 3sigma (0.303)
  - words_num_filter:
      lang: en
      tokenization: true
      min_num: 20
      max_num: 10000
  - word_repetition_filter:
      lang: en
      tokenization: true
      rep_len: 10
      max_ratio: 0.3  # 3sigma

